plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {

    compileSdkVersion 30
    buildToolsVersion "30.0.1"

    defaultConfig {
        applicationId "highonstudy.com"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}

dependencies {

    //Support Library
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    implementation 'com.google.android.material:material:1.2.1'

    //Retrofit, GSON
    implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation("com.squareup.okhttp3:okhttp")
    implementation 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'

    //Firebase
    implementation 'com.google.firebase:firebase-core:17.5.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-messaging-directboot:20.2.0'



    //Glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'

    //Circular Image
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
    implementation 'com.romandanylyk:pageindicatorview:1.0.3'

    implementation 'com.etebarian:meow-bottom-navigation-java:1.2.0'
    implementation 'com.github.armcha:SpaceNavigationView:1.6.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.github.Ferfalk:SimpleSearchView:0.1.6'
    implementation 'com.google.firebase:firebase-ads:19.4.0'
    implementation 'org.jsoup:jsoup:1.11.1'
    implementation 'com.balysv:material-ripple:1.0.2'
    implementation 'com.github.Andy671:Dachshund-Tab-Layout:v0.3.3'
    implementation 'com.github.IslamKhSh:CardSlider:1.0.1'
    implementation 'com.google.android.material:material:1.4.0-alpha02'
    implementation 'com.github.nirwannursabda:expandable-navigation:0.1.2'
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.rom4ek:arcnavigationview:2.0.0'
    implementation 'com.mikhaellopez:circularprogressbar:3.0.3'
    implementation files('libs/YouTubeAndroidPlayerApi.jar')
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.23'
    implementation 'com.github.mehrtarh:CircleButtonBar:v1.1.3'
    implementation 'com.etebarian:meow-bottom-navigation-java:1.2.0'
    implementation 'com.github.angads25:toggle:1.1.0'
}